name: Build job container
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      stackTag:
        description: 'Science Pipelines tag'
        required: true
        default: 'w_latest'
        type: string
      makeProd:
        description: 'Push container with "prod" tag'
        required: false
        type: boolean

jobs:
  build-image:
    name: Build image for nightly reporting
    runs-on: ubuntu-latest
    env:
      STACK_TAG: ${{ inputs.stackTag || 'w_latest' }}
      IMAGE_ID: "ghcr.io/${{ github.repository_owner }}/nightly-reporting"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine the image tag
        run: |
          docker run "lsstsqre/centos:7-stack-lsst_distrib-$STACK_TAG" bash -c "cat conda/envs/lsst-scipipe-*/share/eups/ups_db/global.tags" > eups.tag
          echo "eups tag = $(< eups.tag)"
          echo "IMAGE_TAG=$(< eups.tag)" >> $GITHUB_ENV

      - name: Tag as prod if selected
        if: ${{ inputs.makeProd }}
        run: |
          echo "Tag this image as prod"
          echo "IMAGE_TAG=prod" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_ID }}:${{ env.IMAGE_TAG }}"
          labels: |
            "runnumber=${{ github.run_id }}"
            "stacktag=${{ env.STACK_TAG }}"
          build-args: |
            STACK_TAG=${{ env.STACK_TAG }}
